FROM crpi-bag6znt2buomet4p.cn-beijing.personal.cr.aliyuncs.com/xuruiray/lora:server-slim-base

COPY main/xiaozhi-server .
RUN rm -rf models/SenseVoiceSmall/model.pt models/SenseVoiceSmall/example

CMD ["python", "app.py"]
