FROM crpi-bag6znt2buomet4p.cn-beijing.personal.cr.aliyuncs.com/xuruiray/lora:server-slim-base

COPY app.py config.yaml agent-base-prompt.txt mcp_server_settings.json ./
COPY config/ config/
COPY core/ core/
COPY models/ models/
COPY plugins_func/ plugins_func/
COPY test/ test/

RUN mkdir -p models/snakers4_silero-vad/src/silero_vad/data && \
    curl -sL -o models/snakers4_silero-vad/src/silero_vad/data/silero_vad.onnx \
    https://github.com/snakers4/silero-vad/raw/master/src/silero_vad/data/silero_vad.onnx

CMD ["python", "app.py"]
